### PR TITLE
Use individual lodash packages

### LINKED ISSUE #12: Use individual lodash packages
As the title suggests we can shave off some useless lodash code that can get into a final app bundle. 

It would be even better if we could get rid of it at all.

image

### PR DESCRIPTION
**Pull request by RadValentin**
Fixes #12

### CODE REVIEW

**Comment by RadValentin** [comment]
@skidding @flaviusone Can you take a look?

**Review by ovidiuch — APPROVED** [review]
Great!

**Comment by skidding** [comment]
@RadValentin what's your npm handle? I want to give you publish permissions.

**Review by flaviusone — APPROVED** [review]
:1st_place_medal:

**Comment by RadValentin** [comment]
Heh, managed to drop lodash entirely from the mixin 💃 cc @flaviusone @skidding 


> what's your npm handle? I want to give you publish permissions.

It's [valentin-radulescu-hs](https://www.npmjs.com/~valentin-radulescu-hs)

**Comment by skidding** [comment]
[Done](https://www.npmjs.com/package/react-data-fetch/access). Go ahead and merge & publish.

**Pull request merged**
